definitions:
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.StringResponse:
    properties:
      message:
        type: string
    type: object
  handlers.gameModeCount:
    properties:
      count:
        type: integer
      mode:
        type: string
    type: object
  player.Mode:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-comments:
      Mode_DUO: Duo mode
      Mode_MODE_UNSPECIFIED: Default value
      Mode_SOLO: Solo mode
      Mode_SQUAD: Squad mode
      Mode_TRIO: Trio mode
    x-enum-varnames:
    - Mode_MODE_UNSPECIFIED
    - Mode_SOLO
    - Mode_DUO
    - Mode_TRIO
    - Mode_SQUAD
  player.Player:
    properties:
      area_code:
        description: Area code where the player is located
        type: string
      mode:
        allOf:
        - $ref: '#/definitions/player.Mode'
        description: Current mode the player is playing
      username:
        description: Player's username
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/create-player:
    post:
      consumes:
      - application/json
      description: Create a new player with the provided details
      parameters:
      - description: Player data
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/player.Player'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/player.Player'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Create a new player on a persistant DB just to store permanently
      tags:
      - players
  /api/v1/end-game:
    post:
      consumes:
      - application/json
      description: EndGame the game by taking the userName and areaCode.
      parameters:
      - description: Player data
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/player.Player'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.StringResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: EndGame the game by removing the player from cache for that areaCode
      tags:
      - players
  /api/v1/get-player:
    get:
      consumes:
      - application/json
      description: get a player with the provided userName
      parameters:
      - description: Username of the player
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/player.Player'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: get a exisitng player from a permanent DB
      tags:
      - players
  /api/v1/mode-statistics:
    get:
      consumes:
      - application/json
      description: GetPopularModes fetches popular multiplayer modes based on the
        area code.
      parameters:
      - description: areaCode
        in: query
        name: areaCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.gameModeCount'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Fetches the modes and the count of players for the mode
      tags:
      - players
  /api/v1/start-game:
    post:
      consumes:
      - application/json
      description: StartGame set the Username and mode for the given areaCode(mandatory).
      parameters:
      - description: Player data
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/player.Player'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.StringResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: start the game by adding the player mode to that areaCode
      tags:
      - players
  /api/v1/update-player:
    post:
      consumes:
      - application/json
      description: update a player with the provided details areaCode is mandatory
      parameters:
      - description: Player data
        in: body
        name: player
        required: true
        schema:
          $ref: '#/definitions/player.Player'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/player.Player'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: update a exisitng player on a permanent DB
      tags:
      - players
swagger: "2.0"
